### ISSUE TITLE
Deploying kimios-1.2.1 on CentOS 8

### ISSUE THREAD

**Issue by omaraladin** [kimios/kimios#48]
I'm facing issues after deploying Kimios-1.2.1 on CentOS8, here's the configuration need:
**on kimios.sh**
```
JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.275.b01-1.el8_3.x86_64/jre/"
export $JAVA_HOME
```
**on ~/.bashrc**
```
JAVA_HOME="usr/lib/jvm/java-1.8.0-openjdk"
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.275.b01-1.el8_3.x86_64/bin
```
then I sourced the bachrc file
```
source ~/.bashrc
```
After starting kimios with
```
./kimios.sh start && tail -f logs/*.log
```

Here's some logs
```
<=== localhost.log ===>
INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log No Spring WebApplicationInitializer types detected on classpath

<=== catalina.log ===>
INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/opt/kimios-bundle-1.2.1/webapps/ROOT.war] has finished in [3,409] ms
INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-9999"]
INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["https-jsse-nio-10000"]
INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 14575 ms

<=== localhost.log (this happens when I access localhost:9999) ===>
SEVERE [http-nio-9999-exec-7] org.apache.catalina.core.ApplicationContext.log StandardWrapper.Throwable
 org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'cxf' is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:698)
.
.
.
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```
furthermore:
the index page returns the login screen but without domain in the domain field, that's why I can't even log-in

**Comment by devtom30** [comment]
Hello,
To access Kimios bundle installation, the url is (for localhost) : http://localhost:9999/kimios
Regards,
Tom

**Comment by omaraladin** [comment]
Yeah it works, gonna close this with some details to people who hover over:

- during installation make sure to have JAVA_HOME variable sourced to the user who will run the service
- the first visit while setup, you should visit **http://IP_OR_DOMAIN:9999/kimios**
- Then after Database setup through the website, you can visit http://IP_OR_DOMAIN:9999 directley
