### ISSUE TITLE
kimios and time outs

### ISSUE THREAD

**Issue by oceania-npc** [kimios/kimios#60]
Recently installed kimios and like it.  Using kimios bundle 1.2.1. One issue I am running into is that kimios seems to time out at night, so it has to be restarted in the morning.  Attempted to turn this into a systemd service earlier but had some issues so have been running it with the kimios.sh start command.  Would someone be able to advise either how to properly turn kimios into a systemd service or how to prevent the time out issue at night?
![kimios-data-exception](https://user-images.githubusercontent.com/33435322/129921505-67b04baf-ae9c-4dcf-ad1c-9cd97092805e.png)
![kimios-auth](https://user-images.githubusercontent.com/33435322/129921518-5ee163e4-8236-4f20-a9f5-1730b1012ebe.png)

Attached the stack trace
[kimios-data-source-exception.txt](https://github.com/kimios/kimios/files/7008194/kimios-data-source-exception.txt)

Exception Report:
An exception has occured : Error 03 : Data source exception
                at org.kimios.client.exception.ExceptionHelper.convertException(ExceptionHelper.java:42)
                at org.kimios.client.controller.WorkflowController.getDocumentWorkflowStatusRequests(WorkflowController.java:221)
                at org.kimios.controller.WorkflowControllerWeb.getMyTasks(WorkflowControllerWeb.java:146)
                at org.kimios.controller.WorkflowControllerWeb.execute(WorkflowControllerWeb.java:40)
                at org.kimios.front.MainController.doPost(MainController.java:192)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.kimios.core.filters.CoreFilter.doFilter(CoreFilter.java:56)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.kimios.core.EncodingFilter.doFilter(EncodingFilter.java:40)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:748)

**Comment by devtom30** [comment]
Hello @oceania-npc ,
Nice to read you enjoy Kimios.
Which Kimios distribution do you launch ? Tomcat bundle or Karaf distribution ?

**Comment by oceania-npc** [comment]
Hi devtom30, I installed the kimios bundle and start it with kimios.sh start, so I assume that is the tomcat bundle?  It is possible some permissions need tweaking - what would you recommend for user perms, etc after install?  Did not see anything on the documentation.  Checking the catalina.out logs shows a message (see attached)
![kimios-logs](https://user-images.githubusercontent.com/33435322/130829212-e6be3035-8f70-41a4-9f84-78923e9b9f06.png)  Ideally I would like to integrate it as a systemd service, if possible

**Comment by devtom30** [comment]
Yes you install the tomcat bundle (WAR bundle). I think it comes from the version you use (1.2.1) hat had a problem with DB connection pool.
The current stable version is 1.2.3 : https://github.com/kimios/kimios/releases/download/v1.2.3/kimios-karaf-distribution-1.2.3.tar.gz
At this link, this is the Karaf distribution.
